name: model-training
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - seaborn=0.11.1
  - pandas=1.2.3
  - scikit-learn=0.24.1
  - matplotlib==3.2.2
  - pandas-profiling=3.1.0
  - pillow=8.1.2
  - python=3.8
  - wandb=0.12.7
  - mlflow=1.14.1
  - omegaconf==2.1.1