main:
  project_name: abalone-regression
  experiment_name: dev
  random_seed: 42
data:
  file_url: https://www.kaggle.com/rodolfomendes/abalone-dataset
  test_size: 0.2
  stratify: Age
  val_size: 0.3
  ks_alpha: 0.05
